theme: jekyll-theme-minimal
title: Centre of REAL GitHub Site
GitHub repo: https://github.com/CodeAlba
logo: https://github.com/CentreREAL/CentreREAL.github.io/blob/main/images/Homer_Simpson.png
show_downloads: false
